# Navigation Links

main:
  - name: Home
    url: /
    weight: 10
  - name: Research
    url: /#research
    weight: 20
  - name: Software
    url: /#software
    weight: 25
  - name: Publications
    url: /#publications
    weight: 30
  - name: Awards
    url: /#awards
    weight: 40



